# -*- coding: utf-8 -*-
"""Sesafio Breno Teodomiro - Redução de Dimensionalidade em Imagens para Redes Neurais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UU4VA681Ka6QbGbIm7yZPm38CSM8Swj4

Descrição do Desafio
Seguindo o exemplo do algoritmo de binarização apresentado em nossa última aula, realize a implementação em Python para transformar uma imagem colorida para níveis de cinza (0 a 255) e para binarizada (0 e 255), preto e branco.  



Por meio da imagem é possível visualizar os dois casos esperados:


Figura 1: Lena colorida (imagem de entrada), em níveis de cinza e preto e branca.
"""

import cv2
import urllib.request
import numpy as np
from google.colab.patches import cv2_imshow  # Importa a função para exibição no Colab

# Função para converter uma imagem colorida para tons de cinza
def converter_para_cinza(imagem):
    return cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)

# Função para binarizar a imagem em tons de cinza (preto e branco)
def binarizar(imagem_cinza, limiar=128):
    _, imagem_binaria = cv2.threshold(imagem_cinza, limiar, 255, cv2.THRESH_BINARY)
    return imagem_binaria

def main():
    # URL da imagem Lenna
    url = "https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png"

    # Baixa a imagem a partir da URL
    with urllib.request.urlopen(url) as response:
        image_data = np.asarray(bytearray(response.read()), dtype="uint8")
    imagem_colorida = cv2.imdecode(image_data, cv2.IMREAD_COLOR)

    # Verifica se a imagem foi carregada corretamente
    if imagem_colorida is None:
        print("Erro ao carregar a imagem. Verifique a URL ou sua conexão.")
        return

    # Converte para tons de cinza
    imagem_cinza = converter_para_cinza(imagem_colorida)

    # Binariza a imagem
    imagem_binaria = binarizar(imagem_cinza)

    # Exibe as imagens: original, tons de cinza e binarizada usando cv2_imshow()
    cv2_imshow(imagem_colorida)
    cv2_imshow(imagem_cinza)
    cv2_imshow(imagem_binaria)

if __name__ == '__main__':
    main()